# Generated by Django 4.1.3 on 2022-11-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telesettings',
            name='tg_message',
            field=models.TextField(max_length=200, verbose_name='Текст сообщения'),
        ),
    ]
