# Generated by Django 4.1.3 on 2022-11-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_commentcrm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_statuc',
            new_name='order_status',
        ),
    ]
