# Generated by Django 4.1.3 on 2022-11-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_order_statuc_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
